development:
  adapter: postgresql
  database: my_database_nt_development
  pool: 5
  timeout: 5000
  username: postgres
  password: 
test:
  adapter: postgresql
  database: my_database_nt_development
  pool: 5
  timeout: 5000
  username: postgres
  password:  

production:
  adapter: postgresql
  database: my_database_nt_development
  pool: 5
  timeout: 5000
  username: postgres
  password: 